# Generated by Django 4.2.14 on 2024-08-29 01:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=2000)),
                ('origin', models.TextField(help_text='The origin story of this grudge. Be specific.')),
            ],
            options={
                'verbose_name_plural': 'Stories',
            },
        ),
        migrations.CreateModel(
            name='Grudge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('grudgee_intention', models.IntegerField(choices=[(3, 'a) definitely or probably bad'), (2, 'b) possibly bad'), (1, 'c) not bad')], help_text='How bad was the intention of the grudgee?')),
                ('grudgee_knowledge', models.IntegerField(choices=[(3, 'a) yes, definitely'), (2, 'b) possibly'), (1, 'c) not at all')], help_text='Did they know they were upsetting, hurting, or being unfair to you?')),
                ('seriousness_of_situation', models.IntegerField(choices=[(3, 'a) very serious'), (2, 'b) somewhat serious'), (1, 'c) not very serious')], help_text='How serioius was the situation overall?')),
                ('grudge_effect', models.IntegerField(choices=[(3, 'a) very bad'), (2, 'b) quite bad'), (1, 'c) not so bad')], help_text='Did they cause you real harm?')),
                ('grudgee_skill', models.IntegerField(choices=[(3, 'a) yes'), (2, 'b) maybe'), (1, 'c) no')], help_text='Should or could they have known/done better?')),
                ('harm_level', models.IntegerField(choices=[(3, 'a) yes'), (2, 'b) maybe'), (1, 'c) no')], help_text='Did they cause you real harm?')),
                ('grr_factor', models.IntegerField(choices=[(3, 'a) high'), (2, 'b) medium'), (1, 'c) low')], help_text='Is the `Grrrr!` factor (the extent to which you still strongly feel, Wow, that was so out of order! when you think abou the incident now) of this grudge:')),
                ('grudge_length', models.IntegerField(choices=[(3, "a) for ages; or, for not very long but you know it'll last forever."), (2, "b) for a mediuim length of time; or for a short time and you think you'll hold it for a bit longer but not forever"), (1, "c) for a short time, and you'll probably have given up this grudge by next week")], help_text='Have you held this grudge:')),
                ('grudgee_risk', models.IntegerField(choices=[(0, 'a) no'), (-1, 'b) yes')], help_text="Would something bad or frightening have happened to your grudgee if they hadn't performed the grudge-sparking action?")),
                ('grudge_easily_forgiven', models.IntegerField(choices=[(0, 'a) no'), (-1, 'b) yes')], help_text='Would this grudge be canceled out/terminated if your grudgee apologized fully and wholeheartedly?')),
                ('grudgee_significance', models.IntegerField(choices=[(4, 'a) yes, massively'), (2, 'b) yes, quite a lot'), (0, 'c) not especially—only as a fellow human being')], help_text='Is your grudgee someone who matters to you, and to whom you matter?')),
                ('origin_story', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='grudge', to='grudge_cabinet.story')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
